/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_cdp_jni_test */

#ifndef _Included_com_edu_cdp_jni_test
#define _Included_com_edu_cdp_jni_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_cdp_jni_test
 * Method:    JniGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_edu_cdp_jni_TestJni_JniGetString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
